### ISSUE TITLE
Coefficient evaluation hard coded for P1

### ISSUE THREAD

**Issue by kynan** [gmarkall/manycore_form_compiler#40]
Currently, the generated code for coefficient evaluation has a hard coded assumption of P1 elements:
- There's always a loop over quadrature points. However, in P<sub>0</sub><sup>DG</sup> there is essentially no coefficient evaluation necessary, so the entire loop nest could be dropped and only the field value(s) for the current element loaded from global memory.

**Comment by gmarkall** [comment]
Are you talking about the loop that gets the value of the coefficients at the quadrature points from its values at the nodes? Isn't there always a loop over quadrature points because it's computing the values at the quadrature points?

Also, where is the assumption that elements are P1? I think there's a loop over the basis functions (i_r_0 will be the induction variable in a lot of cases) whose upper bound will vary with the number of basis functions.

Is there another assumption somewhere?

**Comment by dham** [comment]
I don't think that's a P1 assumption. All element integrals can be conducted as a sum over quadrature points. 

What is currently absent is a P0 optimisation because P0 coefficients can go outside the quadrature loop. However this is an OPTIMISATION and we really don't want to look at it until after we have correct code running, however slowly.
